### ISSUE TITLE
Samsung Galaxy A8 A810F

### ISSUE THREAD

**Issue by elelel** [krzk/linux-vendor-backup#2]
Another important Exynos7420 to archive - Samsung A8 A810F for Middle East region and A810YZ for Taiwan. It's of particular interest because it was released about a year later than every other 7420 phones I know of so probably contains latest 7420-related Samsung code. 
The code for Middle East version is available for download from Samsung https://opensource.samsung.com/uploadSearch?searchValue=a810f

Thanks for keeping this archive!

**Comment by krzk** [comment]
Thanks for pointing my attention to this model but I rather won't add more sources for Exynos SoC existing in the repo. The SoC related code usually does not differ between the releases because there is no active development of this part. It's still v3.10, it's still the same vendor code. In the same time any bugs fixed in 2016 were also fixed in newer Android releases for Galaxy S6 which is there already (NN).

**Comment by elelel** [comment]
I see, thank you. I will close this issue then.
